### ISSUE TITLE
Exits with Unhandled exception. Realms.Exceptions.RealmException: Provided schema version 14 is less than last set version 16.

### ISSUE THREAD

**Issue by Xayanide** [kabiiQ/BeatmapExporter#1]
**Description**
OS: `Windows 10 21H2 19044.1826`
osu! Lazer version: `2022.716.1`

**Steps to reproduce**

My osu!Lazer's directory is at `C:\Users\Ava\AppData\Roaming\osu`

1. Download binary from releases page

https://github.com/kabiiQ/BeatmapExporter/releases/download/v1.2.1/BeatmapExporter.exe

3. Run the executable file
> Issue persists even when running as administrator just in case.
4. See command prompt
5. See error
```cs
--- kabii's Lazer Exporter ---

Checking directory: C:\Users\Ava\AppData\Roaming\osu
Run this application with your osu!lazer storage directory as an argument if this is not your osu! data location.
Unhandled exception. Realms.Exceptions.RealmException: Provided schema version 14 is less than last set version 16.
   at Realms.NativeException.ThrowIfNecessary(Func`2 overrider)
   at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey)
   at Realms.RealmConfiguration.CreateHandle(RealmSchema schema)
   at Realms.RealmConfigurationBase.CreateRealm()
   at Realms.Realm.GetInstance(RealmConfigurationBase config)
   at BeatmapExporter.Exporters.Lazer.LazerDB.LazerDatabase.Open()
   at BeatmapExporter.Exporters.Lazer.LazerLoader.Load(String directory)
   at BeatmapExporter.ExporterLoader.Main(String[] args)
   at BeatmapExporter.ExporterLoader.<Main>(String[] args)
```

**Comment by kabiiQ** [comment]
Oh yep, osu!lazer database schema updated a few days ago. 
https://github.com/ppy/osu/blob/master/osu.Game/Database/RealmAccess.cs#L61

Thanks, will push an update in a moment.

**Comment by Xayanide** [comment]
https://github.com/kabiiQ/BeatmapExporter/commit/6c34d465d332b77bb12c18b9fa3ae3dbf1622f6b

**Comment by kabiiQ** [comment]
https://github.com/kabiiQ/BeatmapExporter/releases/tag/v1.2.2
